apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: test
  name: guestbook-ui
  namespace: deafult
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: guestbook-ui
